### PR TITLE
Model <!--ignore--> as its own type and implement the ignoring via an assertion

### PR DESCRIPTION
**Pull request by papandreou**
Fixes `<!--ignore-->` as the top-level to satisfy RHS.

### CODE REVIEW

**Comment by alexjeffburke** [comment]
This is an incredibly elegant solution given the mechanisms available in Unexpected. The modelling of the types in these assertions are such a glove for the DOM that I get this in concept but only just in details.

**Comment by sunesimonsen** [comment]
@papandreou this is brilliant and how I should have made it in the first place - thanks 👍

**Comment by sunesimonsen** [comment]
I'll merge this as @alexjeffburke okayed it.

**Comment by papandreou** [comment]
Great! I wonder if the same idea can be used for `<ignore>`

**Comment by sunesimonsen** [comment]
Yes that would make sense.

**Comment by sunesimonsen** [comment]
You can probably just add the new type to all of the ignore assertions you added.

**Comment by sunesimonsen** [comment]
> Great! I wonder if the same idea can be used for <ignore>

I actually think we should remove the custom element ignore again. It is not documented and can't be used from unexpected-reaction. It doesn't have an element prefix, so it is not a real custom tag, and I prefer to just have one way. Would that be okay with you?

**Comment by alexjeffburke** [comment]
@sunesimonsen I'd like to second you on this one - I think the rationale is solid and, for example, knockout now bans such tag definitions for custom elements outright to avoid problems with them which might be a useful datapoint.

**Pull request merged**
