### PR TITLE
Browser tests

### PR DESCRIPTION
**Pull request by sunesimonsen**
Just another attempt to make the tests run on all of the browsers that we support.

### CODE REVIEW

**Comment by alexjeffburke** [comment]
I think we should try to get this folded in - the branch ensures the library works on IE11 and adds the browserstack glue such that we
can prevent regressions.

@papandreou do you want the have a final peek?

**Comment by papandreou** [comment]
Fixed the u-sinon bug you ran into in https://github.com/unexpectedjs/unexpected-sinon/commit/d0f88e978c8c5c307c9fc1c50fceae681597ff58 / 10.11.2

**Comment by sunesimonsen** [comment]
@papandreou great you fixed it. I still think there is no need use Sinon for these tests.

**Comment by alexjeffburke** [comment]
Looks good! Who wants to take the merge honours :D

**Pull request merged**
