### PR TITLE
Fix: Ignore bug

### PR DESCRIPTION
**Pull request by sunesimonsen**
Fixes: #212

Reproduces a bug where the user is trying to ignore a text node in to satisfy and fixes it.

### CODE REVIEW

**Comment by alexjeffburke** [comment]
Interesting and good catch I'd say!

Just for my understanding, does this come from text nodes being compared as plain strings and thus we end up comparing a text node to an empty object that fails in "to satisfy" when recursing?

**Comment by sunesimonsen** [comment]
The problem is that the RHS is converted into a `to satisfy` object structure. That would mean we would end up comparing a string to the empty object.

**Comment by sunesimonsen** [comment]
> Great catch! I guess expect.it('to be a', 'DOMNode') would also have worked, as all the unexpected-dom types except DOMNodeList inherit from that. Still, there's certainly no harm in using any, and "to be an any" sounds funny :)

Good point. I think that would actually be better and more precise.

**Comment by sunesimonsen** [comment]
Released as unexpected-dom@4.6.2

**Pull request merged**
