### PR TITLE
Modernize the codebase

### PR DESCRIPTION
**Pull request by sunesimonsen**
Fixes:  #210

### CODE REVIEW

**Comment by papandreou** [comment]
Are you using `lebab` for the grunt work?

**Comment by papandreou** [comment]
This has served me well recently:

```
for transform in arrow arrow-return let obj-shorthand obj-method ; do for dir in lib test; do lebab --transform $transform --replace $dir; done ; done
```

**Comment by sunesimonsen** [comment]
> Are you using lebab for the grunt work?

**Comment by sunesimonsen** [comment]
@papandreou there was a good amount of magicpen usage that wasn't using the output argument, so that needed to be fixed manually. 

It is a joy to refactor code bases with this amount of tests.

**Comment by sunesimonsen** [comment]
Most of this PR is automated rewriting, but I also have to do some manual work to get there. I count of the tests to validate the solution.

**Pull request merged**
